import type { ProvisionPage, Review, Version } from '../../types'

type Props = {
  items: Version[]; reviews: Record<string, Review>; chunkPages: Record<string, ProvisionPage>; reviewed: Record<string, boolean>
  publishingId: string; reindexingId: string; loadingChunksId: string
  onInspect: (item: Version) => void; onReviewedChange: (id: string, checked: boolean) => void; onPublish: (item: Version) => void
  onReindex: (item: Version) => void; onChunks: (item: Version, offset?: number) => void; onWithdraw: (item: Version) => void
}

export function VersionList({ items, reviews, chunkPages, reviewed, publishingId, reindexingId, loadingChunksId, onInspect, onReviewedChange, onPublish, onReindex, onChunks, onWithdraw }: Props) {
  return <section className="version-list" aria-label="Danh sách phiên bản văn bản">{items.map(item => {
    const review = reviews[item.id]; const chunkPage = chunkPages[item.id]
    return <article className="version" key={item.id}><div><strong>{item.document_code} — {item.version_label}</strong><p>{item.document_title}</p><small>Lĩnh vực: {item.domain} · Nhóm: {item.category}</small><small>Hiệu lực: {item.effective_from} {item.effective_to ? `đến ${item.effective_to}` : 'đến nay'}</small>
      {review && <details className="review" open><summary>Đã tải {review.provision_count} đơn vị để kiểm tra</summary>{review.provisions.map(p => <div className="provision" key={p.id}><strong>Điều {p.article_no}{p.clause_no ? ` · Khoản ${p.clause_no}` : ''}{p.point_label ? ` · Điểm ${p.point_label}` : ''}{p.chunk_index > 1 ? ` · Phần ${p.chunk_index}` : ''}</strong>{p.heading && <span> — {p.heading}</span>}<p>{p.content}</p></div>)}<label className="review-check"><input type="checkbox" checked={Boolean(reviewed[item.id])} onChange={e => onReviewedChange(item.id, e.target.checked)} /> Tôi đã kiểm tra cấu trúc và đoạn trích phía trên.</label></details>}
      {chunkPage && <section className="published-chunks"><h3>Chunk đã lập chỉ mục ({chunkPage.total})</h3><p className="muted">Đang xem {chunkPage.total === 0 ? 0 : chunkPage.offset + 1}–{Math.min(chunkPage.offset + chunkPage.provisions.length, chunkPage.total)}. Mỗi mục là một đơn vị Điều/Khoản/Điểm đã gửi vào Qdrant.</p>{chunkPage.provisions.map(p => <div className="provision" key={p.id}><strong>#{p.ordinal} · Điều {p.article_no}{p.clause_no ? ` · Khoản ${p.clause_no}` : ''}{p.point_label ? ` · Điểm ${p.point_label}` : ''}{p.chunk_index > 1 ? ` · Phần ${p.chunk_index}` : ''}</strong>{p.heading && <span> — {p.heading}</span>}<p>{p.content}</p></div>)}<div className="chunk-pagination"><button type="button" disabled={loadingChunksId === item.id || chunkPage.offset === 0} onClick={() => onChunks(item, Math.max(0, chunkPage.offset - chunkPage.limit))}>← Trước</button><button type="button" disabled={loadingChunksId === item.id || chunkPage.offset + chunkPage.provisions.length >= chunkPage.total} onClick={() => onChunks(item, chunkPage.offset + chunkPage.limit)}>Sau →</button></div></section>}
    </div><div className="version-actions"><span className={`badge ${item.status.toLowerCase()}`}>{item.status}</span>{item.status === 'PENDING_REVIEW' && <><button type="button" onClick={() => onInspect(item)}>Kiểm tra cấu trúc</button>{review && <button type="button" disabled={!reviewed[item.id] || publishingId === item.id} onClick={() => onPublish(item)}>{publishingId === item.id ? 'Đang xuất bản…' : 'Duyệt & xuất bản'}</button>}</>}{item.status === 'PUBLISHED' && <><button type="button" disabled={loadingChunksId === item.id} onClick={() => onChunks(item)}>{loadingChunksId === item.id ? 'Đang tải chunk…' : chunkPage ? 'Ẩn chunk' : 'Xem chunk đã lập chỉ mục'}</button><button type="button" disabled={reindexingId === item.id} onClick={() => onReindex(item)}>{reindexingId === item.id ? 'Đang lập chỉ mục…' : 'Lập chỉ mục lại metadata'}</button><button className="danger-button" type="button" onClick={() => onWithdraw(item)}>Thu hồi</button></>}</div></article>
  })}</section>
}
